config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'search', to: "dogs#search"
  resources :dogs do
    resources :bookings, only: [:new, :show, :create]
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new
  end

    def show
        @booking = Booking.find(params[:id])
    end

  def create
    @booking = Booking.new(booking_params)

    @dog = Dog.find(params[:dog_id])
    @booking.dog = @dog


    if user_signed_in?
      @user = current_user
    else
      @user = User.first
    end

    @booking.user = @user
    if @booking.save
      redirect_to dog_booking_path(@booking.dog, @booking)
        else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    if params[:query].present?
      @dogs = Dog.where("name ILIKE ?", "#{params[:query]}")
    else
    @dogs = Dog.all
    end
  end

  def show
      @dog = Dog.find(params[:id])
      @address = @dog.address
      @dogs = Dog.near(@address, 0)

      @markers = @dogs.geocoded.map do |dog|
          {
            lat: dog.latitude,
            lng: dog.longitude
          }
        end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@dog, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="container">

<h1>New Booking</h1>

<%= render 'form' %>
</div>

app/views/bookings/show.html.erb
<div>
  <div class="container">
    <h1>Congratulations!!</h1>
    <p>You booked</p>
    <h1><%= @booking.dog.name %></h1>
    <div id="button">
    <%= link_to "Go Back To My Fellow Chi-Chi's", dogs_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="flex-container">

  <%= form_tag dogs_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a dog"
  %>
  <%= submit_tag "Search", class: "btn btn-primary searchbutton" %>
<% end %>

<% @dogs.each do |dog| %>
<div class="card-product">
  <img src="<%= dog.img_url %>">
  <div class="card-product-infos">
    <h2><%= dog.name %></h2>
    <p><%= dog.description %></p>  
  </div>
  <div id="img">
  <%= image_tag("5star.png") %>
   <div id="button"> 
    <%= link_to 'Book Me', dog_path(dog), class: "btn btn-flat" %>
   </div>
 </div>
</div>

<% end %>

</div>

app/views/dogs/show.html.erb
<div class="container">


  <div class="dog-card-wrapper">

  <h1><%= @dog.name %></h1>
  <h2> I'm adorable!</h2>
      <div class="dog-card-d">
        <div class="img-text-container">

            <div class="img-container">
            <img src="<%= @dog.img_url %>" alt="">
            </div>

            

            <div class="text-container">
              <p class="description"><%= @dog.description %></p>
          
              <div class="button-container">

                <p class="secondary-p">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec facilisis ex, vitae scelerisque odio.
                </p>
            
                <div id="link"><div class="btn-container">
                <%= link_to 'Book This Chi', new_dog_booking_path(@dog), class: "btn btn-flat" %></div>
                </div>
              </div>
            </div>


              
        </div>   

          <div class="map-container-d">
            <div id="map"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          
          </div>
      </div>

          <div id="link"><%= link_to 'View Other Chihuhuas', dogs_path, class: "" %>
          </div>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChihuahuaRentals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' unless params[:action] == "home"%>
    <%# end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <div class="banner-content">
       <%= image_tag "chi-chi-logo.png", alt: "alttext", width: 300 %>
       <p>Rent a bitchy chi to feel happy about your miserable life </p>
       <div id="link"><%= link_to 'Start Renting Now', dogs_path, class: "btn btn-flat" %></div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav">
<div class="nav-logo-img"></div>

</div>